---
platforms:
  - name: molecule-pptp-${CI_JOB_ID:-1}
    image: centos/systemd:latest
    pull: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /usr/sbin/init
    stop_signal: "SIGRTMIN+3"
    privileged: true
    capabilities:
      - SYS_ADMIN  # For systemd
provisioner:
  name: ansible
  log: True
  options:
    vvv: False
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: True
      callback_whitelist: profile_tasks
    diff:
      always: True
  lint:
    name: ansible-lint
    options:
      force-color: True
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    verbose: true
driver:
  name: docker
lint:
  name: yamllint
dependency:
  name: galaxy
